import { TestimonialsReport, WcagGrade } from '../types';

const GRADE_EMOJI: Record<WcagGrade, string> = {
  AAA:        '🟢',
  AA:         '🔵',
  'AA-Large': '🟡',
  Fail:       '🔴',
};

function gradeIcon(grade: WcagGrade): string {
  return `${GRADE_EMOJI[grade]} \`${grade}\``;
}

export function generateMarkdownReport(report: TestimonialsReport): string {
  const date   = new Date(report.meta.generatedAt).toUTCString();
  const s      = report.legibility.summary;
  const ae     = report.aesthetic;
  const access = report.accessibility;

  const lines: string[] = [
    `# Testimonials Generator — Full Report`,
    ``,
    `> Generated: ${date} | v${report.meta.generatorVersion} | ${report.meta.totalLogos} logos | Overall: ${gradeIcon(report.overallGrade)}`,
    ``,
    `---`,
    ``,
    `## Summary`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Total logos | ${report.meta.totalLogos} |`,
    `| Pass on light bg | ${s.logosPassingOnLight}/${report.meta.totalLogos} |`,
    `| Pass on dark bg | ${s.logosPassingOnDark}/${report.meta.totalLogos} |`,
    `| Pass on both | ${s.logosPassingBoth}/${report.meta.totalLogos} |`,
    `| Logos with issues | ${s.logosWithIssues.length > 0 ? s.logosWithIssues.join(', ') : 'none'} |`,
    ``,
    ...report.overallSummary.map(l => `- ${l}`),
    ``,
    `---`,
    ``,
    `## Legibility Analysis`,
    ``,
    `| Logo | On White | On Light Gray | On Dark Gray | On Black | Light ✓ | Dark ✓ |`,
    `|------|----------|---------------|--------------|----------|---------|--------|`,
    ...report.legibility.perLogo.map(r =>
      `| **${r.displayName}** | ${r.onWhite.ratio}:1 ${r.onWhite.grade} | ${r.onLightGray.ratio}:1 ${r.onLightGray.grade} | ${r.onDarkGray.ratio}:1 ${r.onDarkGray.grade} | ${r.onBlack.ratio}:1 ${r.onBlack.grade} | ${r.bestForLight ? '✅' : '❌'} | ${r.bestForDark ? '✅' : '❌'} |`
    ),
    ``,
    `### Per-Logo Recommendations`,
    ``,
    ...report.legibility.perLogo.map(r => {
      const issueText = r.issues.length > 0
        ? r.issues.map(i => `  - ⚠️ ${i}`).join('\n')
        : `  - ✅ No issues detected.`;
      return `**${r.displayName}** — ${gradeIcon(r.overallOnLight)} light / ${gradeIcon(r.overallOnDark)} dark\n${issueText}\n> ${r.recommendation}`;
    }),
    ``,
    `---`,
    ``,
    `## Size Configurations`,
    ``,
    `| Size | Height | Usable | Notes |`,
    `|------|--------|--------|-------|`,
    ...report.legibility.perSize.map(r =>
      `| \`${r.size}\` | ${r.pixelHeight}px | ${r.minimumSizeCompliant ? '✅' : '❌'} | ${r.recommendation} |`
    ),
    ``,
    `---`,
    ``,
    `## Aesthetic Analysis`,
    ``,
    `| Dimension | Score |`,
    `|-----------|-------|`,
    `| Overall | **${ae.overallScore}/100** |`,
    `| Visual Balance | ${ae.visualBalance}/100 |`,
    `| Size Harmony | ${ae.sizeHarmony}/100 |`,
    `| Logo Count | ${ae.logoCountScore}/100 |`,
    `| Spacing Consistency | ${ae.spacingConsistency}/100 |`,
    ``,
    `**Breakdown:** ${ae.breakdown.logoCount} logos, mean aspect ratio ${ae.breakdown.meanAspectRatio}:1, CV=${ae.breakdown.aspectRatioCv}, suggested layout: \`${ae.breakdown.suggestedLayout}\``,
    ``,
    ae.suggestions.length > 0
      ? `**Suggestions:**\n${ae.suggestions.map(sg => `- ${sg}`).join('\n')}`
      : `✅ No aesthetic suggestions.`,
    ``,
    `---`,
    ``,
    `## Accessibility Audit`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Alt text coverage | ${access.altTextCoverage}% |`,
    `| Pass on light bg | ${access.contrastCompliance.onLight}% |`,
    `| Pass on dark bg | ${access.contrastCompliance.onDark}% |`,
    `| Overall WCAG level | ${gradeIcon(access.wcagLevel)} |`,
    ``,
    access.issues.length > 0
      ? `**Issues:**\n${access.issues.map(i => `- ⚠️ ${i}`).join('\n')}`
      : `✅ No accessibility issues.`,
    ``,
    `**Recommendations:**`,
    ...access.recommendations.map(r => `- ${r}`),
    ``,
    `---`,
    ``,
    `_Report generated by [testimonials-generator](https://github.com/digitalby/digitalby) v${report.meta.generatorVersion}_`,
  ];

  return lines.join('\n');
}

/** Terse CI-friendly summary (used as GitHub Actions job summary) */
export function generateSummaryMarkdown(report: TestimonialsReport): string {
  const s = report.legibility.summary;
  const gradeEmoji = GRADE_EMOJI[report.overallGrade];

  const failingLight = report.legibility.perLogo.filter(r => !r.bestForLight).map(r => r.displayName);
  const failingDark  = report.legibility.perLogo.filter(r => !r.bestForDark).map(r => r.displayName);

  return [
    `## ${gradeEmoji} Testimonials Report — \`${report.overallGrade}\``,
    ``,
    `| | |`,
    `|---|---|`,
    `| Logos | ${report.meta.totalLogos} |`,
    `| Pass on light bg | ${s.logosPassingOnLight}/${report.meta.totalLogos} |`,
    `| Pass on dark bg | ${s.logosPassingOnDark}/${report.meta.totalLogos} |`,
    `| Pass on both | ${s.logosPassingBoth}/${report.meta.totalLogos} |`,
    `| Aesthetic score | ${report.aesthetic.overallScore}/100 |`,
    `| Accessibility | ${gradeIcon(report.accessibility.wcagLevel)} |`,
    ``,
    failingLight.length > 0 ? `**⚠️ Low contrast on light bg:** ${failingLight.join(', ')}` : `✅ All logos pass on light backgrounds.`,
    failingDark.length  > 0 ? `**⚠️ Low contrast on dark bg:** ${failingDark.join(', ')}`  : `✅ All logos pass on dark backgrounds.`,
    ``,
    report.aesthetic.suggestions.length > 0
      ? `**Aesthetic notes:** ${report.aesthetic.suggestions[0]}`
      : '',
  ].filter(l => l !== undefined).join('\n');
}
